baseURL: http://www.example.com
title: Home
theme: hugo-coder
languageCode: en
defaultContentLanguage: en
paginate: 20
enableEmoji: yes
markup:
  highlight:
    style: github-dark
params:
  author: Sydne Guevara M.Sc., Ph.D.
  avatarURL: images/avatar.jpg
  colorScheme: auto
  commit: https://github.com/luizdepra/hugo-coder/tree/
  customCSS: []
  customJS: []
  customRemoteJS: []
  customSCSS: []
  dateFormat: January 2, 2006
  description: Sydne Guevara's personal website
  hideColorSchemeToggle: no
  info:
    - Molecular Biologist
    - Genomics, Genetic Engineering & Bioinformatics for Translational Research
  keywords: personal, researcher
  maxSeeAlsoItems: 5
  rtl: no
  since: 2023
  social:
    - icon: fa fa-2x fa-github
      name: Github
      url: https://github.com/sydneguevara
      weight: 1
    - icon: fa fa-2x fa-linkedin
      name: LinkedIn
      url: https://www.linkedin.com/in/sydne-guevara/
      weight: 3
    - icon: fa fa-2x fa-graduation-cap
      name: Google Scholar
      url: https://scholar.google.com/citations?user=ct6dQkkAAAAJ&hl=en
      weight: 4
taxonomies:
  author: authors
  category: categories
  series: series
  tag: tags
languages:
  en:
    languageName: ':us:'
    menu:
      main:
        - name: About
          url: about/
          weight: 1
        - name: Publications
          url: Publications/
          weight: 2
        - name: Projects
          url: Projects/
          weight: 3
        - name: Blog
          url: blog/
          weight: 4
        - name: Contact me
          url: contact/
          weight: 5
  pt-br:
    languageName: ':es:'
    menu:
      main:
        - name: Perfil
          url: about/
          weight: 1
        - name: Publicaciones
          url: Publicaciones/
          weight: 2
        - name: Proyectos
          url: projects/
          weight: 3
        - name: Blog
          url: Blog/
          weight: 4
        - name: Contacto
          url: contact/
          weight: 5
    params:
      author: Sydne Guevara M.Sc., Ph.D.
      description: Página profesional de Sydne Guevara
      info:  
          - Bióloga Molecular
          - 
      keywords: blog,desenvolvedor,pessoal
    title: Inicio
